name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Copiar arquivo JSON
      run: cp db.json $GITHUB_WORKSPACE

    - name: Configurar pacotes npm
      run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.GITHUB_TOKEN }}

    - name: Instalar peaceiris/actions-gh-pages
      run: npm install -g gh-pages

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
