name: Atualizar API JSON

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configurar pacotes npm
      run: npm config set //registry.npmjs.org/:_authToken ${{ secrets.GITHUB_TOKEN }}

    - name: Instalar peaceiris/actions-gh-pages
      run: npm install -g gh-pages

    - name: Publicar no GitHub Pages
      run: |
        gh-pages -d . -b master
